In [82]:
import pandas as pd #need to import pandas

In [83]:
parks = pd.DataFrame({"Park": ["Oak", "Pine","Maple","Cedar"],"Area":[12,25,18,40], "Visitors":[120,250,180,310]})
print(parks) #the data frame is called parks. the data frame includes the coluns park, area, and visitors.

    Park  Area  Visitors
0    Oak    12       120
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

In [84]:
parks["Visitors"] #in the parks dataframe, what are the values for visitors THIS IS A SERIES

0    120
1    250
2    180
3    310
Name: Visitors, dtype: int64

In [85]:
parks[["Park","Visitors"]] #show me a dataframe with parks and the number of visitors for each park

    Park  Visitors
0    Oak       120
1   Pine       250
2  Maple       180
3  Cedar       310

In [86]:
parks.iloc[0] #what is in the first row

Park        Oak
Area         12
Visitors    120
Name: 0, dtype: object

In [87]:
parks.iloc[1:4] #what are in the first three rows?

    Park  Area  Visitors
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

In [88]:
parks.iloc[1:4][["Park","Area"]] #show me the first three rows but only the area and park

    Park  Area
1   Pine    25
2  Maple    18
3  Cedar    40

In [89]:
large_parks= parks[parks["Area"]>20].copy() #make a new dataframe called large_parks which has parks over an area of 20, make a copy and print the new dataframe out

print(large_parks)

    Park  Area  Visitors
1   Pine    25       250
3  Cedar    40       310

In [90]:
parks.columns =["Name","Area_ha","Annual_Visitors"] #rename using .columns, check them again
parks.head()

    Name  Area_ha  Annual_Visitors
0    Oak       12              120
1   Pine       25              250
2  Maple       18              180
3  Cedar       40              310

In [91]:
values = pd.Series(["12.5","18.0","missing","22.5"])
values = pd.to_numeric(values, errors="coerce")
print(values)

0    12.5
1    18.0
2     NaN
3    22.5
dtype: float64

In [92]:
parks.sort_values("Annual_Visitors", ascending=False)

    Name  Area_ha  Annual_Visitors
3  Cedar       40              310
1   Pine       25              250
2  Maple       18              180
0    Oak       12              120

In [93]:
values = [5,12,3,20]

for value in values:
    if value > 10:
     print(value)

12
20

In [94]:
import pandas as pd

values = [5, 12, 3, 20]

s = pd.Series(values)

s > 10

0    False
1     True
2    False
3     True
dtype: bool