In [5]:
import pandas as pd

In [8]:
parks = pd.DataFrame({"Park": ["Oak", "Pine","Maple","Cedar"],"Area":[12,25,18,40], "Visitors":[120,250,180,310]})
print(parks)

    Park  Area  Visitors
0    Oak    12       120
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

In [9]:
parks["Visitors"]

0    120
1    250
2    180
3    310
Name: Visitors, dtype: int64

In [11]:
parks[["Park","Visitors"]]

    Park  Visitors
0    Oak       120
1   Pine       250
2  Maple       180
3  Cedar       310

In [12]:
parks.iloc[0]

Park        Oak
Area         12
Visitors    120
Name: 0, dtype: object

In [13]:
parks.iloc[1:4]

    Park  Area  Visitors
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

In [14]:
parks.iloc[1:4][["Park","Area"]]

    Park  Area
1   Pine    25
2  Maple    18
3  Cedar    40

In [20]:
large_parks= parks[parks["Area"]>20].copy()

print(large_parks)

    Park  Area  Visitors
1   Pine    25       250
3  Cedar    40       310