Python Indexing Refresher

In [1]:
locations= ["Oak", "Pine", "Maple", "Cedar", "Elm"]

In [2]:
locations[0]

'Oak'

In [3]:
locations[4]

'Elm'

In [4]:
locations[1:4]

['Pine', 'Maple', 'Cedar']

In [5]:
locations[2]

'Maple'

In [6]:
points = [[100,200],[140,230],[180,260],[120,280]]
points[2]

[180, 260]

In [7]:
points[2][1]

260

In [8]:
points[1][0]

140

Pandas Indexing Refresher

In [9]:
import pandas as pd

df=pd.DataFrame({
                "name": ["Oak","Pine","Maple", "Cedar"],
                "ft":[25,48,31,60],
                "zone":["A","B","A","B"]
})

In [10]:
df["ft"]

0    25
1    48
2    31
3    60
Name: ft, dtype: int64

In [11]:
df[["name","ft"]]

    name  ft
0    Oak  25
1   Pine  48
2  Maple  31
3  Cedar  60

In [12]:
df.iloc[1]

name    Pine
ft        48
zone       B
Name: 1, dtype: object

In [13]:
df.iloc[0:3]

    name  ft zone
0    Oak  25    A
1   Pine  48    B
2  Maple  31    A

In [14]:
df[df["ft"] > 30]

    name  ft zone
1   Pine  48    B
2  Maple  31    A
3  Cedar  60    B

Moving to NumPy arrays

In [15]:
import numpy as np

points=np.array([[100,200],
                 [140,230],
                 [180,260],
                 [120,280]])

In [16]:
points.shape

(4, 2)

In [17]:
points[0]

array([100, 200])

In [18]:
points[0,1]

np.int64(200)

In [19]:
points[1:3]

array([[140, 230],
       [180, 260]])

In [23]:
points[2][1]

np.int64(260)

In [24]:
points[2,1]

np.int64(260)

Vectorized operations

In [20]:
shift = np.array([10,20])
points + shift

array([[110, 220],
       [150, 250],
       [190, 280],
       [130, 300]])

Distance and Pandas Connection

In [21]:
a = np.array([100,200])
b = np.array([140,230])
distance = np.sqrt(((a - b)** 2).sum())

In [22]:
distance

np.float64(50.0)